# Generated by Django 5.2.11 on 2026-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_STATUS', 'Changement de statut'), ('NEW_MESSAGE', 'Nouveau Message'), ('JOB_ALERT', 'Alerte Emploi'), ('SYSTEM', 'Système'), ('MATCH_FOUND', 'Match IA Trouvé'), ('KYC_REJECTED', 'Document Rejeté'), ('KYC_SUBMITTED', 'Document Soumis'), ('KYC_COMPLETED', 'Dossier KYC Complet'), ('PAYMENT_RECEIVED', 'Paiement Reçu')], default='SYSTEM', max_length=20),
        ),
    ]
