services:
  - type: web
    name: travago-backend
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: travago-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.12.0"

databases:
  - name: travago-db
    plan: free
