# Generated by Django 5.2.11 on 2026-02-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('missions', models.TextField()),
                ('requirements', models.TextField()),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage')], default='CDI', max_length=20)),
                ('experience_level', models.CharField(choices=[('JUNIOR', 'Junior (0-2 ans)'), ('INTERMEDIATE', 'Intermédiaire (2-5 ans)'), ('SENIOR', 'Sénior (5-10 ans)'), ('EXPERT', 'Expert (10+ ans)')], default='INTERMEDIATE', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('is_ia_boosted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('AI_REVIEW', 'Analyse IA'), ('SHORTLISTED', 'Retenu'), ('REJECTED', 'Refusé'), ('PLACED', 'Placé')], default='PENDING', max_length=20)),
                ('matching_score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.candidateprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
            ],
            options={
                'unique_together': {('job_offer', 'candidate')},
            },
        ),
    ]
