# Generated by Django 5.2.11 on 2026-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sector',
            field=models.CharField(choices=[('TECH', 'Informatique / Tech'), ('FINANCE', 'Finance / Banque'), ('HEALTH', 'Santé / Médical'), ('CONSTRUCTION', 'BTP / Construction'), ('AGRICULTURE', 'Agriculture'), ('TURISM', 'Tourisme / Hôtellerie'), ('EDUCATION', 'Éducation / Formation'), ('TRANSPORT', 'Transport / Logistique'), ('COMMERCE', 'Commerce / Vente'), ('SERVICES', 'Services à la personne'), ('INDUSTRY', 'Industrie'), ('ADMIN', 'Administration / RH')], default='TECH', max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance')], default='CDI', max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(choices=[('STAGIAIRE', 'Stagiaire / Étudiant'), ('JUNIOR', 'Junior (0-2 ans)'), ('INTERMEDIATE', 'Intermédiaire (2-5 ans)'), ('SENIOR', 'Sénior (5-10 ans)'), ('EXPERT', 'Expert (10+ ans)')], default='INTERMEDIATE', max_length=20),
        ),
    ]
