# Generated by Django 5.2.11 on 2026-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_is_boosted_joboffer_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
