# Generated by Django 5.2.11 on 2026-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joboffer_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Nouvelle'), ('AI_REVIEW', 'Analyse IA'), ('SHORTLISTED', 'En Revue'), ('INTERVIEW', 'Entretien'), ('REJECTED', 'Refusé'), ('PLACED', 'Embauché')], default='PENDING', max_length=20),
        ),
    ]
