# Generated by Django 5.2.11 on 2026-02-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du poste à pourvoir', max_length=255)),
                ('description', models.TextField()),
                ('budget_credits', models.IntegerField(default=250)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SOURCING', 'Recherche de Talents'), ('AI_ANALYSIS', 'Analyse IA v2.5'), ('VALIDATION', 'Validation Humaine'), ('SHORTLIST_READY', 'Shortlist Prête'), ('COMPLETED', 'Terminé')], default='SOURCING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_requests', to='users.companyprofile')),
                ('matches', models.ManyToManyField(blank=True, related_name='placement_matches', to='users.candidateprofile')),
            ],
        ),
    ]
