# Generated by Django 5.2.11 on 2026-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='candidates/kyc/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='reliability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='video_pitch',
            field=models.URLField(blank=True, help_text='Lien vers la vidéo de présentation', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
