# Generated by Django 5.2.11 on 2026-02-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidateprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat de Travail / Stage'), ('OTHER', 'Autre Document')], max_length=20)),
                ('file', models.FileField(upload_to='candidates/kyc/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.candidateprofile')),
            ],
        ),
    ]
