# Generated by Django 5.2.11 on 2026-02-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyprofile_phone_candidatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
