# Generated by Django 5.2.11 on 2026-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Non Vérifié'), ('PENDING', 'En attente de validation'), ('VERIFIED', 'Vérifié / Certifié'), ('REJECTED', 'Rejeté')], default='UNVERIFIED', max_length=20),
        ),
    ]
