# Generated by Django 5.2.11 on 2026-02-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidateprofile_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedocument',
            name='document_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('DIPLOMA', 'Diplôme'), ('CERTIFICATE', 'Certificat de Travail / Stage'), ('CV', 'Curriculum Vitae'), ('OTHER', 'Autre Document')], max_length=20),
        ),
    ]
