# Generated by Django 5.2.11 on 2026-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
