# Generated by Django 5.2.11 on 2026-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='unlocked_candidates',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_companies', to='users.candidateprofile'),
        ),
    ]
